posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'), 
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create_category'),
]

postsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    name = models.CharField(max_length=255)
    content = models.TextField()
    post_date = models.DateTimeField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.post_date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_date = models.DateTimeField()

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)
    def __str__(self):
        return f'{self.name}  ({self.text})'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'content',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'content':'Conteúdo',
            'poster_url': 'URL do Poster',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

posts/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.urls.base import reverse_lazy
from .models import Post, Comment, Category
import datetime
from django.utils import timezone
from .forms import PostForm, CommentForm
from django.views import generic

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create.html'
    success_url = reverse_lazy('posts:index')

class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:index')

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:index')

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(name__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'posts/search.html', context)

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            comment_date=datetime.datetime.now(tz=timezone.utc),
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/category.html'


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'posts/create_category.html'
    fields = ['name', 'text', 'posts']
    success_url = reverse_lazy('posts:category')

def CategoryIndividual(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category' : category}
    return render(request, 'post/category.html', context)

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/category.html
{% extends 'base.html' %}

{% block title %}
Category
{% endblock title %}

{% block content %}
<h2>Categoria dos Posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <h3>{{category.name}} ( {{ category.text }}) </h3>
        </header>
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.poster_url }}"
                        alt="Poster do filme {{ post.name}}"></a>
                <p>{{ post.name }} ({{ post.post_date }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    <a href="{% url 'posts:create_category' %}"><button>Crie sua Categoria</button></a>
</section>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentário Post {{ post.name }} ({{ post.post_date }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/create_category.html
{% extends 'base.html' %}

{% block title %}
Criar Filme
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'posts:create_category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o post "{{ post.name }} ({{ post.post_date }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.post_date }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Post {{ post.name }} ({{ post.post_date }})</h2>

<section class="dados-de-filme">
    <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
    <ul>
        <li>Titúlo: {{ post.name }}</li>
        <li>Data de Publicação: {{ post.post_date }} </li>
        <li>Conteúdo: {{ post.content }} </li>
        {% if post.category_set.all %}
            <li>Incluso nas Categorias: {{ post.category_set.all|join:", " }} </li>
        {% endif %}
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }} ({{comment.comment_date}})
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este post.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Crie seu Comentário</button></a>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'posts:search' %}">Buscar Posts</a></p>
    <p>Não encontrou o post? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.poster_url }}"
                alt="Poster do filme {{ post.name}}"></a> 
        <p>{{ post.name }} ({{ post.post_date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Posts por Titúlo</h2>
<form action="{% url 'posts:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <img src="{{ post.poster_url }}" alt="Poster do filme {{ post.name}}">
        <p>{{ post.name }} ({{ post.post_date }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post para a busca.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Filme {{ post.name }}({{ post.release_year}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Esse site cria noticias falsas e/ou exageradas para gerar posts sensacionalistas em base capas de filmes</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Sejam Bem Vindos!</i></h1>
<p>A Página que cria noticias sensacionalistas em base de capas de filmes</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo3.svg' %}"> </a> 
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li> 
                <li><a href="{% url 'posts:category' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright  Rogério Pinho Borges dos Santos 2021</small>
        </p>
    </footer>
</body>

</html>